# Generated by Django 4.2.7 on 2025-04-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_alter_task_task_description'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='task_manage_source_13f0ef_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('microsoft', 'Microsoft')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
