# Generated by Django 4.2.7 on 2025-04-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0002_userprofile_weightentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='weekly_weight_loss_goal',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Weekly weight loss goal in pounds', max_digits=3),
        ),
    ]
